// - SYSTEM
export const SET_OS = 'SET_OS';
export const SET_RSA = 'SET_RSA';
export const SET_CONTROL_BAR_POSITION = 'SET_CONTROL_BAR_POSITION';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';

// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';

//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

//SOCKET
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const MESSAGE_STATE_FLAG = 'MESSAGE_STATE_FLAG';

//WALLET
export const SET_INVOICE_CATEGORY = 'SET_INVOICE_CATEGORY';
export const SET_INVOICE_USER = 'SET_INVOICE_USER';
